### ISSUE TITLE
I want to save model but get an error

### ISSUE THREAD

**Issue by akashso** [bryanlimy/tf2-transformer-chatbot#12]
i got an non implemented error when i try to save model in h5 format 

NotImplementedError: Layer PositionalEncoding has arguments in `__init__` and therefore must override `get_config`.

can you please help

**Comment by bryanlimy** [comment]
Hi, you can check how to save custom model here: https://www.tensorflow.org/tutorials/keras/save_and_load#saving_custom_objects

**Comment by akashso** [comment]
i updated all the layers. please take a look https://colab.research.google.com/drive/1jjpG1xsdwjZPeDPM35M60pOzwR_7Im5I

this time i gettin NotImplementedError: Learning rate schedule must override get_config

is this any bug of tensorflow

**Comment by bryanlimy** [comment]
Try this https://github.com/bryanlimy/tf2-transformer-chatbot/pull/13
