### ISSUE TITLE
Saving model??

### ISSUE THREAD

**Issue by Rob-Byrne** [bryanlimy/tf2-transformer-chatbot#16]
I have been banging my head trying to save the model for later evaluation - do you have code that will do this (i.e. generate config for the model of embed for model.save() functionality?

**Comment by bryanlimy** [comment]
Hi @Rob-Byrne 
You can call `save_weights` and `load_weights`
```
filename = 'weights.h5'
model.save_weights(filename)

new_model = transformer(hparams)
new_model.load_weights(filename)
```

**Comment by frankplus** [comment]
`model.save_weights(filename)` does not save the optimizer state, so it's not possible to restore and resume the training after it's stopped.
by using `model.save()` it should save the optimizer state but I cannot make it to work, it says "Not JSON Serializable"

**Comment by bryanlimy** [comment]
Yes @frankplus, with model subclassing, we have to overwrite the `get_config` and `from_config` methods, see https://www.tensorflow.org/guide/keras/save_and_serialize#custom_objects.

This was already done in an early PR https://github.com/bryanlimy/tf2-transformer-chatbot/pull/13 though only in jupyter notebook. You can take a look, should be relatively simple to port copy the changes over.

**Comment by aqibfayyaz** [comment]
> `model.save_weights(filename)` does not save the optimizer state, so it's not possible to restore and resume the training after it's stopped.
> by using `model.save()` it should save the optimizer state but I cannot make it to work, it says "Not JSON Serializable"

Hi were you successful?

**Comment by aqibfayyaz** [comment]
> Hi @Rob-Byrne
> You can call `save_weights` and `load_weights`
> 
> ```
> filename = 'weights.h5'
> model.save_weights(filename)
> 
> new_model = transformer(hparams)
> new_model.load_weights(filename)
> ```

please can you upload the code with saves the model too?
=

**Comment by bryanlimy** [comment]
https://github.com/bryanlimy/tf2-transformer-chatbot/pull/23
