### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.api._v2.keras.layers' has no attribute 'LayerNormalization'

### ISSUE THREAD

**Issue by jinfagang** [bryanlimy/tf2-transformer-chatbot#4]
Why does this got?

```
AttributeError: module 'tensorflow.python.keras.api._v2.keras.layers' has no attribute 'LayerNormalization'

```

**Comment by bryanlimy** [comment]
Hi, `tensorflow==2.0.0-alpha0` has LayerNormalization under `tf.keras.layers.experimental`, whereas the latest nightly version or `tensorflow==2.0.0-beta0` has it under `tf.keras.layers`, so please update your TF version :)

**Comment by jinfagang** [comment]
@bryanlimy  Thanks! beta is just arrived!
