### ISSUE TITLE
ValueError: tf.function-decorated function tried to create variables on non-first call.

### ISSUE THREAD

**Issue by hno1993** [bryanlimy/tf2-transformer-chatbot#8]
I am using window 10 operating system 

and when I try to run this project using Colab notebook

I get this **error**
 
`ValueError: tf.function-decorated function tried to create variables on non-first call`

 in this **step**:

`model.fit(dataset, epochs=EPOCHS)` 

`Epoch 1/20`
`     1/Unknown - 8s 8s/step`
`---------------------------------------------------------------------------`
`ValueError                                Traceback (most recent call last)`
`<ipython-input-42-d13425ded836> in <module>()`
`      1 EPOCHS = 20`
`      2 `
`----> 3 model.fit(dataset, epochs=EPOCHS)`

`45 frames`
`/tensorflow-2.0.0-rc2/python3.6/tensorflow_core/python/eager/def_function.py in` `invalid_creator_scope(*unused_args, **unused_kwds)`
`    411       """Disables variable creation."""`
`    412       raise ValueError(`
`--> 413           "tf.function-decorated function tried to create "`
`    414           "variables on non-first call.")`
`    415 `

`ValueError: tf.function-decorated function tried to create variables on non-first call.`

anyone could know what is the problem?
it will mean the world to me :(

note': I haven't altered anything from the original source code

**Comment by smorbrt** [comment]
Same thing for me.. Did u solve it?
Do u maybe know any other chatbot repository with tf 2 code?
:P

**Comment by bryanlimy** [comment]
https://github.com/bryanlimy/tf2-transformer-chatbot/commit/af911a4ec2541edc202d197c0d36abd2437f4343

It should run now

**Comment by smorbrt** [comment]
Thx! have a nice day (:
