### ISSUE TITLE
Interacting with "chatbot"

### ISSUE THREAD

**Issue by ShyExtrovert1** [bryanlimy/tf2-transformer-chatbot#9]
I dont see how you can chat with your chatbot. All i can see is training model and thats it. So please dont misinform ppl better change the title to tf2-model or smthing..
Or if i am maybe wrong tell me/us how we can actually chat with it. Thank you

**Comment by bryanlimy** [comment]
Hi did you check the tutorial and Colab notebook on how to train and test the model?

**Comment by ShyExtrovert1** [comment]
Yeah when im already there why not check how to make bot by myself. Bro whats the point then,is it hard for you to just implement that code. Im not going to argue with you.. i checked that website nad its not even the same.. when i execute predict it says missing arguments,models and shit.Screw this ill just find another one

**Comment by ShyExtrovert1** [comment]
u can close this bs now. delete or whatever

**Comment by bryanlimy** [comment]
I think the point of the tutorial is to learn how to build and train the model, and the code are already there. Thank you for the informative conversation tho.
